-- logging_lcaj táblába történő hibaesetek rögzítése

CREATE OR REPLACE PROCEDURE record_error_lcaj(PRC VARCHAR2) AUTHID DEFINER  AS 

   PRAGMA AUTONOMOUS_TRANSACTION;
   l_mesg  VARCHAR2(32767) := SQLERRM;
 
BEGIN

	EXECUTE IMMEDIATE' INSERT INTO logging_lcaj (created_on, info, proc_name, message, backtrace)
	VALUES (TO_CHAR(CURRENT_TIMESTAMP, ''YYYY.MM.DD HH24:MI:SS.FF''), ''ERROR'', '''|| PRC ||''', '''|| l_mesg ||''', sys.DBMS_UTILITY.format_error_backtrace)';
		
		
   COMMIT;
END;


-- táblák tartalmának törlése / 1

create or replace PROCEDURE truncate_table(P_TABLE VARCHAR2) AUTHID DEFINER  AS 
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE ' || P_TABLE || ' DROP STORAGE';  
END truncate_table;

-- táblák tartalmának törlése / 2

create or replace PROCEDURE delete_table(P_TABLE VARCHAR2) AUTHID DEFINER  AS 
BEGIN
  EXECUTE IMMEDIATE 'DELETE FROM ' || P_TABLE || '';  
END delete_table;


-- táblák törlése

create or replace PROCEDURE drop_table(P_TABLE VARCHAR2) AUTHID DEFINER  AS 
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ' || P_TABLE || '';
END drop_table;


-- ez a tábla az LC-be kerüljön
CREATE TABLE logging_lcaj
(
   created_on      VARCHAR2(30)
 , info 		   VARCHAR2 (30)
 , proc_name	   VARCHAR2 (30)	
 , message   	   VARCHAR2 (4000)
 , backtrace       CLOB

)
;

-- az aktuális év LCxx_F sémájában létre kell hozni ezt a táblát, valamint ALL jogot kell adni a táblán az LC usernek 
CREATE TABLE LCAJ5_180112_V05
(
TEV VARCHAR2(10),
teaor VARCHAR2(20),
MEGNEV VARCHAR2(500),
LCAJ581_q1 NUMBER(10,3),
LCAJ582_q1 NUMBER(10,3),
LCAJ583_q1 NUMBER(10,3),
LCAJ581_q2 NUMBER(10,3),
LCAJ582_q2 NUMBER(10,3),
LCAJ583_q2 NUMBER(10,3),
LCAJ581_q3 NUMBER(10,3),
LCAJ582_q3 NUMBER(10,3),
LCAJ583_q3 NUMBER(10,3),
LCAJ581_q4 NUMBER(10,3),
LCAJ582_q4 NUMBER(10,3),
LCAJ583_q4 NUMBER(10,3),
LCAJ584_q1 NUMBER(10,3),
LCAJ585_q1 NUMBER(10,3),
LCAJ586_q1 NUMBER(10,3),
LCAJ584_q2 NUMBER(10,3),
LCAJ585_q2 NUMBER(10,3),
LCAJ586_q2 NUMBER(10,3),
LCAJ584_q3 NUMBER(10,3),
LCAJ585_q3 NUMBER(10,3),
LCAJ586_q3 NUMBER(10,3),
LCAJ584_q4 NUMBER(10,3),
LCAJ585_q4 NUMBER(10,3),
LCAJ586_q4 NUMBER(10,3)
)
;



-- PACKAGE 

create or replace PACKAGE LCAJ  AUTHID CURRENT_USER AS 
TYPE T_HONAP IS TABLE OF VARCHAR2(50 CHAR) INDEX BY PLS_INTEGER;
TYPE T_MHO IS TABLE OF VARCHAR2(50 CHAR) INDEX BY PLS_INTEGER;
TYPE T_MHO_OUT IS TABLE OF VARCHAR2(50 CHAR) INDEX BY PLS_INTEGER;
TYPE T_TEAOR IS TABLE OF VARCHAR2(50 CHAR) INDEX BY PLS_INTEGER;
TYPE T_M0581 IS TABLE OF VARCHAR2(50 CHAR) INDEX BY PLS_INTEGER;
TYPE T_ENG_LIST IS TABLE OF VARCHAR2(500 CHAR) INDEX BY PLS_INTEGER;
TYPE T_ENG_MEGNEV IS TABLE OF VARCHAR2(500 CHAR) INDEX BY PLS_INTEGER;
TYPE T_OSSZEG IS TABLE OF VARCHAR2(1000 CHAR) INDEX BY PLS_INTEGER;
TYPE T_HUN_LIST IS TABLE OF VARCHAR2(50 CHAR) INDEX BY PLS_INTEGER;
TYPE T_HUN_OSSZEG IS TABLE OF VARCHAR2(1000 CHAR) INDEX BY PLS_INTEGER;
TYPE T_out_table_01 IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_out_table_02 IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_out_table_03 IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_out_table_04 IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_in_table_01 IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_in_table_02 IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_in_table_03 IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_LCAJ_TABLES IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_LCAJ_TABLES_a IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_LCAJ_INPUT_LTSZ IS TABLE OF VARCHAR2(100 CHAR) INDEX BY PLS_INTEGER;
TYPE T_create_lcaj_01_LCAJ581 IS TABLE OF VARCHAR2(200 CHAR) INDEX BY PLS_INTEGER;
TYPE T_create_lcaj_01_LCAJ582 IS TABLE OF VARCHAR2(200 CHAR) INDEX BY PLS_INTEGER;
TYPE T_create_lcaj_01_kozf_n IS TABLE OF VARCHAR2(200 CHAR) INDEX BY PLS_INTEGER;

procedure ins_LCAJ_letszam(P_EVSZAM VARCHAR2);
END LCAJ;


